<?php
function alien_types()
{
    return [
        'bio_sectoid',
        'mech_drone',
        'bio_thinman',
        'mech_seeker',
        'bio_outsider',
        'mech_floater',
        'bio_chryssalid',
        'bio_zombie',
        'bio_muton',
        'mech_cyberdisk',
        'mech_mechtoid',
        'bio_berserker',
        'bio_sectoidcommander',
        'mech_heavyfloater',
        'bio_mutonelite',
        'mech_sectopod',
        'bio_ethereal',
        'exalt_operative',
        'exalt_sniper',
        'exalt_heavy',
        'exalt_medic',
        'exalt_eliteoperative',
        'exalt_elitesniper',
        'exalt_eliteheavy',
        'exalt_elitemedic',
    ];
}
